// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ujpdzlhtoehfhbakqieg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVqcGR6bGh0b2VoZmhiYWtxaWVnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ1MjQ0MjgsImV4cCI6MjA2MDEwMDQyOH0.vM0NliqvwFlh4cfRG0-E9LvpL80U5KFmjlCtmqz8-4g";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);